# Generated by Django 5.0.14 on 2026-06-20 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fen', models.CharField(max_length=255)),
                ('moves', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=1500)),
                ('themes', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('homework_type', models.CharField(choices=[('pdf', 'PDF Assignment'), ('lichess_study', 'Lichess Study Link'), ('pgn_analysis', 'PGN Analysis Task'), ('quiz', 'Chess Quiz'), ('puzzles', 'Tactical Puzzles')], max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lichess_study_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pgn_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to='academy.coach')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academy.student')),
            ],
            options={
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_notes', models.TextField(blank=True, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_pgn', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('coach_feedback', models.TextField(blank=True, null=True)),
                ('coach_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='homework.homeworkassignment')),
            ],
        ),
    ]
