# Generated by manual addition on 2026-06-22
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='homework.puzzle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to='academy.student')),
            ],
        ),
    ]
