services:
  # Django ASGI Backend running Daphne
  - type: web
    name: chesshub-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "./backend/start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DJANGO_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: chesshub-redis
          property: connectionString
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Redis instance for Channels websocket broker
  - type: redis
    name: chesshub-redis
    ipAllowList: []
