# Generated by Django 5.0.14 on 2026-06-20 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('chess_level', models.CharField(choices=[('beginner', 'Beginner Foundations'), ('intermediate', 'Intermediate Development'), ('advanced', 'Advanced Training'), ('tournament', 'Tournament Excellence')], default='beginner', max_length=50)),
                ('preferred_time', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contact Established'), ('scheduled', 'Demo Scheduled'), ('completed', 'Demo Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('classes', 'Live Classes'), ('achievements', 'Student Achievements'), ('tournaments', 'Tournaments'), ('certificates', 'Certificates')], max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('drive_file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
