# Generated by manual addition on 2026-06-21

from django.db import migrations, models

def migrate_status_forwards(apps, schema_editor):
    DemoBooking = apps.get_model('academy', 'DemoBooking')
    mapping = {
        'pending': 'new',
        'scheduled': 'demo_scheduled',
        'completed': 'demo_completed',
        'cancelled': 'lost'
    }
    for old, new in mapping.items():
        DemoBooking.objects.filter(status=old).update(status=new)

def migrate_status_backwards(apps, schema_editor):
    DemoBooking = apps.get_model('academy', 'DemoBooking')
    mapping = {
        'new': 'pending',
        'demo_scheduled': 'scheduled',
        'demo_completed': 'completed',
        'lost': 'cancelled',
        'converted': 'completed'
    }
    for new, old in mapping.items():
        DemoBooking.objects.filter(status=new).update(status=old)


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_demobooking_galleryimage'),
    ]

    operations = [
        migrations.RunPython(migrate_status_forwards, migrate_status_backwards),
        migrations.AlterField(
            model_name='demobooking',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'New Lead'),
                    ('contacted', 'Contact Established'),
                    ('demo_scheduled', 'Demo Scheduled'),
                    ('demo_completed', 'Demo Completed'),
                    ('converted', 'Converted to Active Student'),
                    ('lost', 'Lost Lead')
                ],
                default='new',
                max_length=20
            ),
        ),
    ]
