# Generated by manual addition on 2026-06-22
from django.db import migrations, models
import django.db.models.deletion
import academy.models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_update_demobooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='starting_rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='student',
            name='target_rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='student',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='coach_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weekly_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='target_attendance_rate',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='student',
            name='target_homework_rate',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='student',
            name='roadmap',
            field=models.JSONField(blank=True, default=academy.models.default_roadmap),
        ),
        migrations.CreateModel(
            name='MonthlyStudentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_month', models.CharField(max_length=7)),
                ('attendance_rate', models.FloatField()),
                ('homework_rate', models.FloatField()),
                ('rating_growth', models.IntegerField()),
                ('puzzle_accuracy', models.FloatField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('coach_feedback', models.TextField(blank=True, null=True)),
                ('next_month_goals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='academy.student')),
            ],
            options={
                'unique_together': {('student', 'report_month')},
            },
        ),
    ]
