# Generated by Django 5.0.14 on 2026-06-22 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_student_development_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformanceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blunders_avg', models.FloatField(default=0.0)),
                ('mistakes_avg', models.FloatField(default=0.0)),
                ('inaccuracies_avg', models.FloatField(default=0.0)),
                ('acpl', models.FloatField(default=0.0)),
                ('opening_perf_rating', models.IntegerField(default=1500)),
                ('middlegame_perf_rating', models.IntegerField(default=1500)),
                ('endgame_perf_rating', models.IntegerField(default=1500)),
                ('puzzle_accuracy', models.FloatField(default=100.0)),
                ('puzzle_rating', models.IntegerField(default=1500)),
                ('solve_speed_seconds', models.FloatField(default=0.0)),
                ('strongest_theme', models.CharField(default='Tactics', max_length=100)),
                ('weakest_theme', models.CharField(default='None', max_length=100)),
                ('improvement_trend', models.JSONField(blank=True, default=list)),
                ('fork_weakness', models.IntegerField(default=0)),
                ('pin_weakness', models.IntegerField(default=0)),
                ('skewer_weakness', models.IntegerField(default=0)),
                ('king_safety_issues', models.IntegerField(default=0)),
                ('calculation_issues', models.IntegerField(default=0)),
                ('endgame_issues', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('risk_alerts', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profile', to='academy.student')),
            ],
        ),
    ]
