# Generated by Django 5.0.14 on 2026-06-26 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_studentperformanceprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobooking',
            name='status',
            field=models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contact Established'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('converted', 'Converted to Active Student'), ('lost', 'Lost Lead')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='scheduled_start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
