# Generated by Django 5.0.14 on 2026-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Academy Manager'), ('coach', 'Coach'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
