# Generated by Django 5.0.14 on 2026-06-20 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('xp_bonus', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_streak', models.IntegerField(default=0)),
                ('weekly_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_info', to='academy.student')),
            ],
        ),
        migrations.CreateModel(
            name='XpTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_earned', models.IntegerField()),
                ('reason', models.CharField(choices=[('puzzle_solve', 'Solved Chess Puzzle'), ('homework_completion', 'Completed Homework'), ('badge_award', 'Earned Achievement Badge'), ('streak_bonus', 'Streak Active Bonus'), ('class_attendance', 'Attended Class Session')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_history', to='academy.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_students', to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_earned', to='academy.student')),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
